name: demoCall
on:
  push:
    branches:
      - develop
jobs:
  call-workflow-in-local-repo:
    uses: OrcaSlide/orcaslide/.github/workflows/reutilizar.yml@develop
    with: 
      username: Esto se manda desde demoCall