name: reutilizar
on:
  push:
    branches:
      - develop
  workflow_call:
    inputs:
      username:
        description: "Hola soy jorge"
        default: "JMENDEZ"
        required: false
        type: string
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Vamos a imprimer los nombres del user
        run: echo ${{ inputs.username }}