name: reutilizar
on:
  workflow_call:
    inputs:
      username:
        description: 'Hola soy jorge'
        default: 'JMENDEZ'
        required: false
        type: string
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrando el nombre de usuario
        run: echo el nombre del usuario es ${{ inputs.username }}